name: Sync with godot-vision-cone

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 1 * *'     # once per month, 8:00 AM UTC on the 1st
  workflow_dispatch:        # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wrapper repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone upstream addon
        run: |
          git clone --depth 1 https://github.com/fahall/godot-vision-cone.git upstream

      - name: Debug upstream contents
        run: |
          ls -al upstream
          ls -al upstream/addons
          
      - name: Sync vision_cone_2d files
        run: |
          find . -mindepth 1 -not -path "./.git*" -not -path "./.github*" -not -path "./upstream*" -exec rm -rf {} +
          cp -r upstream/addons/vision_cone_2d/. ./

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git rm --cached -r upstream 2>/dev/null || true
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync from upstream godot-vision-cone"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
